# This file is intended
# for configuring a test pod
# to demonstrate the working of the application.
# Here you can see an example of running a pod with a nginx container

# Container image variables
container:
  name: nginx # Container name
  image: nginx:1.24.0 # Container image that you deploy to the cluster
  process: nginx # Main process in container

# Name and identifier variables
metadata:
  deploymentName: nginx-webhook # Set the unique name for deployment schema
  appName: nginx-app # Application name label

# Name of Container Monitor App service account
serviceAccount: integrity # Service account name

# Number of replicas
replicaCount: 1

rsyslog:
  enabled: false

monitoringConfig:
  processName: nginx # Container process name
  mountPaths: # Paths to monitoring
    - bin
    - usr/bin
