containers:
  - name: hasher-sidecar
    image: { { .Values.sideCar.image } }
    imagePullPolicy: { { .Values.pullPolicy | default "Always" } }
    args:
      - --db-host={{ .Values.sideCar.db.host }}
      - --db-port={{ .Values.sideCar.db.port }}
      - --db-name={{ .Values.sideCar.db.name }}
      - --duration-time={{ .Values.sideCar.durationTime }}
      - --count-workers={{ .Values.sideCar.workers }}
      - --proc-dir={{ .Values.sideCar.procDir }}
      - --algorithm={{ .Values.sideCar.algorithm }}
      - --splunk-url={{ .Values.sideCar.splunk.url }}
      - --splunk-token={{ .Values.sideCar.splunk.token }}
      - --splunk-insecure-skip-verify={{ .Values.sideCar.splunk.insecureSkipVerify }}
    envFrom:
      - secretRef:
          name: { { .Values.sideCar.secretName } }
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: DEPLOYMENT_TYPE
        value: deployment
    resources:
      { { .Values.sideCar.resources | toYaml | trimSuffix "\n" | nindent 8 } }
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    stdin: true
    tty: true
