apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.deploymentName }}
  labels:
    app: {{ .Values.metadata.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
      annotations:
        integrity-monitor.scnsoft.com/inject: "true"
        integrity-monitor.scnsoft.com/process-image: {{ .Values.container.process }}={{ .Values.container.image }}
        {{ .Values.monitoringConfig.processName }}.integrity-monitor.scnsoft.com/monitoring-paths: {{ join "," .Values.monitoringConfig.mountPaths }}
    spec:
      serviceAccountName: {{ .Release.Name}}-{{ .Values.serviceAccount }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          stdin: true
          tty: true
