apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.deploymentName }}
  labels:
    app: {{ .Values.metadata.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        hasher-certificates-injector-sidecar: "true"
    spec:
      shareProcessNamespace: true
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          stdin: true
          tty: true
