containers:
  - name: hasher-sidecar
    image: {{ .Values.sideCar.image }}
    imagePullPolicy: {{ .Values.sideCar.pullPolicy | default "Always" }}
    args:
      - --db-host={{ .Values.sideCar.db.host }}
      - --db-port={{ .Values.sideCar.db.port }}
      - --db-name={{ .Values.sideCar.db.name }}
      - --db-user={{ .Values.sideCar.db.username }}
      - --duration-time={{ .Values.sideCar.durationTime }}
      - --count-workers={{ .Values.sideCar.workers }}
      - --proc-dir={{ .Values.sideCar.procDir }}
      - --algorithm={{ .Values.sideCar.algorithm }}
      - --splunk-url={{ .Values.sideCar.splunk.url }}
      - --splunk-token={{ .Values.sideCar.splunk.token }}
      - --splunk-insecure-skip-verify={{ .Values.sideCar.splunk.insecureSkipVerify }}
      {{- if .Values.sideCar.syslog.enabled }}
      - --syslog-enabled={{ .Values.sideCar.syslog.enabled }}
      - --syslog-host={{ .Values.sideCar.syslog.host }}
      - --syslog-port={{ .Values.sideCar.syslog.port }}
      - --syslog-proto={{ .Values.sideCar.syslog.proto }}
      - --cluster-name={{ .Values.cluster }}
      {{- end }}
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ .Values.sideCar.secretName }}
            key: password
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: DEPLOYMENT_TYPE
        value: deployment
    resources: {{ .Values.sideCar.resources | toYaml | trimSuffix "\n" | nindent 8 }}
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - "[ -f /tmp/integrity-monitor ] && pidof integritySum"
      initialDelaySeconds: 10
      periodSeconds: 5
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    stdin: true
    tty: true
