containers:
  - name: integrity-sidecar
    image: {{ .Values.sideCar.image }}
    imagePullPolicy: {{ .Values.sideCar.pullPolicy | default "Always" }}
    args:
      - --duration-time={{ .Values.sideCar.durationTime }}
      - --count-workers={{ .Values.sideCar.workers }}
      - --algorithm={{ .Values.sideCar.algorithm }}
      {{- if .Values.sideCar.splunk.enabled }}
      - --splunk-enabled={{ .Values.sideCar.splunk.enabled }}
      - --splunk-url={{ required "url is required" .Values.sideCar.splunk.url }}
      - --splunk-token={{ required "token is required" .Values.sideCar.splunk.token }}
      - --splunk-insecure-skip-verify={{ .Values.sideCar.splunk.insecureSkipVerify }}
      {{- end }}
      {{- if .Values.sideCar.syslog.enabled }}
      - --syslog-enabled={{ .Values.sideCar.syslog.enabled }}
      - --syslog-host={{ required "host is required" .Values.sideCar.syslog.host }}
      - --syslog-port={{ required "port is required" .Values.sideCar.syslog.port }}
      - --syslog-proto={{ required "proto is required" .Values.sideCar.syslog.proto }}
      - --cluster-name={{ .Values.cluster }}
      {{- end }}
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: DEPLOYMENT_TYPE
        value: deployment
    resources: {{ .Values.sideCar.resources | toYaml | trimSuffix "\n" | nindent 8 }}
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - "[ -f /tmp/integrity-monitor ] && pidof {{ .Values.sideCar.liveness.appName }}"
      initialDelaySeconds: 10
      periodSeconds: 5
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    stdin: true
    tty: true
