apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "integrity-injector.fullname" . }}-sidecar-config
  labels:
    {{- include "integrity-injector.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/*.yaml").AsConfig . | indent 2 }}
