{{- $caPrefix := printf "%s-ca" .Release.Name }}
{{- $app := include "integrity-injector.fullname" . }}
{{- $ca := genCA $caPrefix 365 }}
{{- $cn := .Release.Name }}
{{- $altName := printf "%s.%s.svc" $app .Release.Namespace}}
{{- $cert := genSignedCert $cn nil (list $altName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $app }}-certs
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.webhook.serverCrtFile }}: {{ b64enc $cert.Cert }}
  {{ .Values.webhook.serverKeyFile }}: {{ b64enc $cert.Key }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "integrity-injector.name" . }}
webhooks:
  - name: k8s-webhook-injector.default.svc.cluster.local
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ $app }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.webhook.path }}
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
{{- include "integrity-injector.NamespaceSelector" . | indent 4 }}
