kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.appName }}
spec:
  selector:
    component: {{ .Values.appName }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
