{{- $caPrefix := printf "%s-ca" .Release.Name }}
{{- $ca := genCA $caPrefix 365 }}
{{- $cn := .Release.Name }}
{{- $altName := printf "%s.%s.svc" .Release.Name .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.confName }}
  namespace: {{ .Release.Namespace }}
data:
  server.crt: {{ b64enc $cert.Cert }}
  server.key: {{ b64enc $cert.Key }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.appName }}
webhooks:
  - name: k8s-webhook-injector.default.svc.cluster.local
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ .Values.appName }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.path }}
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
{{- include "injector.NamespaceSelector" . | indent 4 }}
